[package]
name = "genBTCAddresss"
version = "1.0.0"
edition = "2021"

[dependencies]
rand_core = { version = "0.5", features = ["getrandom"] }
secp256k1 = "0.27"
bs58 = "0.4"
bech32 = "0.8"
bip39 = "1.2.0"
bip32 = "0.2.2"
bitcoin_hashes = "0.11"
